export const habilidades=[
    {id:1,
     item:"img/habilidades/01.svg",
    state:false
    },
    {id:2,
        item:"img/habilidades/02.svg",
       state:false
    },
    {id:3,
    item:"img/habilidades/03.svg",
    state:false
    },
    {id:4,
    item:"img/habilidades/04.svg",
    state:false
    },
    {id:5,
    item:"img/habilidades/05.svg",
    state:false
    },
    {id:6,
    item:"img/habilidades/06.svg",
    state:false
     },
     {id:7,
        item:"img/habilidades/07.svg",
        state:false
        },
        {id:8,
        item:"img/habilidades/08.svg",
        state:false
        },
        {id:9,
        item:"img/habilidades/10.svg",
        state:false
         },
         {id:10,
        item:"img/habilidades/11.svg",
         state:false
         },
         {id:11,
         item:"img/habilidades/12.svg",
          state:false
             },
             {id:12,
                item:"img/habilidades/13.svg",
                 state:false
                 },
]